timeout: "1200s"
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: southamerica-east1
  _REPO: app-repo
  _SERVICE: hiperban-staging

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA']

  # deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run','deploy','$_SERVICE',
        '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA',
        '--region=$_REGION','--platform=managed','--allow-unauthenticated',
        '--port=8080',
        '--add-cloudsql-instances=hiperban-plataforma:southamerica-east1:hiperban-sql',
        '--set-secrets=DATABASE_URL=DATABASE_URL_STAGING:latest,ASAAS_API_KEY=ASAAS_API_KEY_STAGING:latest',
        '--set-env-vars=NODE_ENV=staging,NEXT_PUBLIC_ENV=preview'
      ]
